application: gsdmarin-info
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
 
- url: /pages
  static_dir: pages

- url: /.*
  script: main.app
  login: required

# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest

- name: MySQLdb
  version: "latest"

- name: jinja2
  version: "latest"

- name: django
  version: "1.4"
# [END libraries]
